-- MySQL Script generated by MySQL Workbench
-- Sat 23 Jun 2018 08:00:26 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ulbora_api_gateway
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ulbora_api_gateway
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ulbora_api_gateway` DEFAULT CHARACTER SET utf8 ;
USE `ulbora_api_gateway` ;

-- -----------------------------------------------------
-- Table `ulbora_api_gateway`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_api_gateway`.`client` (
  `client_id` BIGINT NOT NULL,
  `api_key` VARCHAR(500) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `level` VARCHAR(45) NOT NULL DEFAULT 'small',
  `paid` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`client_id`),
  UNIQUE INDEX `client_id_UNIQUE` (`client_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_api_gateway`.`rest_route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_api_gateway`.`rest_route` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `route` VARCHAR(100) NOT NULL,
  `client_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `client_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_rest_route_client1_idx` (`client_id` ASC),
  UNIQUE INDEX `index4` (`route` ASC, `client_id` ASC),
  CONSTRAINT `fk_rest_route_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `ulbora_api_gateway`.`client` (`client_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_api_gateway`.`route_url`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_api_gateway`.`route_url` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT 'blue',
  `url` VARCHAR(200) NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `rest_route_id` BIGINT NOT NULL,
  `rest_route_client_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `rest_route_id`, `rest_route_client_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_route_url_rest_route1_idx` (`rest_route_id` ASC, `rest_route_client_id` ASC),
  CONSTRAINT `fk_route_url_rest_route1`
    FOREIGN KEY (`rest_route_id` , `rest_route_client_id`)
    REFERENCES `ulbora_api_gateway`.`rest_route` (`id` , `client_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_api_gateway`.`route_performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_api_gateway`.`route_performance` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `calls` BIGINT NOT NULL DEFAULT 0,
  `latency_ms_total` BIGINT NOT NULL DEFAULT 0,
  `entered` DATETIME NOT NULL,
  `route_url_id` BIGINT NOT NULL,
  `route_url_rest_route_id` BIGINT NOT NULL,
  `route_url_rest_route_client_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `route_url_id`, `route_url_rest_route_id`, `route_url_rest_route_client_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_route_performance_route_url1_idx` (`route_url_id` ASC, `route_url_rest_route_id` ASC, `route_url_rest_route_client_id` ASC),
  CONSTRAINT `fk_route_performance_route_url1`
    FOREIGN KEY (`route_url_id` , `route_url_rest_route_id` , `route_url_rest_route_client_id`)
    REFERENCES `ulbora_api_gateway`.`route_url` (`id` , `rest_route_id` , `rest_route_client_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_api_gateway`.`route_error`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_api_gateway`.`route_error` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` INT NOT NULL,
  `message` VARCHAR(600) NOT NULL,
  `entered` DATETIME NOT NULL,
  `route_url_id` BIGINT NOT NULL,
  `route_url_rest_route_id` BIGINT NOT NULL,
  `route_url_rest_route_client_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `route_url_id`, `route_url_rest_route_id`, `route_url_rest_route_client_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_route_error_route_url1_idx` (`route_url_id` ASC, `route_url_rest_route_id` ASC, `route_url_rest_route_client_id` ASC),
  CONSTRAINT `fk_route_error_route_url1`
    FOREIGN KEY (`route_url_id` , `route_url_rest_route_id` , `route_url_rest_route_client_id`)
    REFERENCES `ulbora_api_gateway`.`route_url` (`id` , `rest_route_id` , `rest_route_client_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_api_gateway`.`breaker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_api_gateway`.`breaker` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `failure_threshold` INT NOT NULL,
  `failure_count` INT NOT NULL DEFAULT 0,
  `last_failure_time` DATETIME NULL,
  `health_check_time_seconds` INT NOT NULL,
  `failover_route_name` VARCHAR(100) NULL,
  `open_fail_code` INT NOT NULL,
  `route_url_id` BIGINT NOT NULL,
  `route_url_rest_route_id` BIGINT NOT NULL,
  `route_url_rest_route_client_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `route_url_id`, `route_url_rest_route_id`, `route_url_rest_route_client_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_breaker_route_url1_idx` (`route_url_id` ASC, `route_url_rest_route_id` ASC, `route_url_rest_route_client_id` ASC),
  CONSTRAINT `fk_breaker_route_url1`
    FOREIGN KEY (`route_url_id` , `route_url_rest_route_id` , `route_url_rest_route_client_id`)
    REFERENCES `ulbora_api_gateway`.`route_url` (`id` , `rest_route_id` , `rest_route_client_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
